apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-default
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/apple/pkl-k8s-examples.git
    targetRevision: main
    path: pkl/basic
    plugin:
      name: pkl
