apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: pkl-cmp
          command: [/var/run/argocd/argocd-cmp-server]
          args: [--loglevel, debug]
          image: inoc603e/argocd-pkl
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /tmp
              name: pkl-plugin-tmp
      volumes:
        - emptyDir: {}
          name: pkl-plugin-tmp
